# Generated by Django 2.1.5 on 2019-02-14 04:20

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import read_statistics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10)),
                ('created_time', models.DateTimeField(default=False)),
                ('commander', models.CharField(max_length=5)),
                ('commander_phone', models.CharField(max_length=15)),
                ('chief_duty', models.CharField(max_length=5)),
                ('chief_phone', models.CharField(max_length=15)),
                ('operator', models.CharField(max_length=5)),
                ('operator_phone', models.CharField(max_length=15)),
                ('police_duty', models.CharField(max_length=5)),
                ('police_post', models.CharField(max_length=5)),
                ('emergency_police', models.CharField(max_length=5)),
                ('emergency_vehicle', models.CharField(max_length=5)),
                ('external_transfer', models.CharField(max_length=5)),
                ('num_workers', models.CharField(max_length=5)),
                ('training_all', models.CharField(max_length=5)),
                ('training_day', models.CharField(max_length=5)),
                ('confinement_all', models.CharField(max_length=5)),
                ('confinement_day', models.CharField(max_length=5)),
                ('isolation_all', models.CharField(max_length=5)),
                ('isolation_day', models.CharField(max_length=5)),
                ('death', models.CharField(max_length=5)),
                ('leave_and_back', models.CharField(max_length=5)),
                ('judicial_all', models.CharField(max_length=5)),
                ('judicial_day', models.CharField(max_length=5)),
                ('social_all', models.CharField(max_length=5)),
                ('social_day', models.CharField(max_length=5)),
                ('freed_people', models.CharField(max_length=5)),
                ('parole', models.CharField(max_length=5)),
                ('reconfirm', models.CharField(max_length=5)),
                ('outside_prison', models.CharField(max_length=5)),
                ('outside_prison_death', models.CharField(max_length=5)),
                ('charter', models.CharField(max_length=5)),
                ('detective_relatives_all', models.CharField(max_length=5)),
                ('detective_relatives_day', models.CharField(max_length=5)),
                ('police_on_post', models.CharField(max_length=5)),
                ('exotic_vehicle', models.CharField(max_length=5)),
                ('video_alarm', models.CharField(max_length=5)),
                ('perimeter_alarm', models.CharField(max_length=5)),
                ('grid_alarm', models.CharField(max_length=5)),
                ('violation_msg', ckeditor_uploader.fields.RichTextUploadingField()),
                ('leave_prison_msg', ckeditor_uploader.fields.RichTextUploadingField()),
                ('important_msg', ckeditor_uploader.fields.RichTextUploadingField()),
                ('emergencies_msg', ckeditor_uploader.fields.RichTextUploadingField()),
                ('disposal_msg', ckeditor_uploader.fields.RichTextUploadingField()),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('Operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_time'],
            },
            bases=(models.Model, read_statistics.models.ReadNumExpandMethod),
        ),
        migrations.CreateModel(
            name='MsgType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='msg',
            name='msg_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msg.MsgType'),
        ),
    ]
