# Generated by Django 2.1.5 on 2019-02-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='police_on_post',
            new_name='foreign_workers',
        ),
        migrations.RenameField(
            model_name='msg',
            old_name='police_post',
            new_name='registered_police',
        ),
    ]
